name: test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Install Lua
        uses: hishamhm/gh-actions-lua@master
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - name: Install LuaRocks
        uses: hishamhm/gh-actions-luarocks@master

      - name: Build
        run: |
          luarocks make --dev
          luarocks install busted

      - name: Test
        run: busted -o utfTerminal build/

